services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo1:/data/db

  backend:
    build: ../backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - ../frontend:/app/frontend
    environment:
      - MONGO_URI=mongodb://mongo1:27017/uploadDB?replicaSet=rs0
    depends_on:
      - mongo1
